### ISSUE TITLE
Here are some warning

### ISSUE THREAD

**Issue by whisper-bye** [wooorm/mdast-github#1]
env: with npm and webpack
I  don't know what to do to solve the problem

WARNING in ./~/mdast-github/index.js
Critical dependencies:
368:19-370:14 the request of a dependency is an expression
 @ ./~/mdast-github/index.js 368:19-370:14

WARNING in ./~/mdast-github/LICENSE
Module parse failed: /Users/user-mac/Desktop/workspace/test/www/node_modules/mdast-github/LICENSE Line 1: Unexpected identifier
You may need an appropriate loader to handle this file type.
| (The MIT License)
|
| Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>
 @ ./~/mdast-github ^\.\/.*$

WARNING in ./~/mdast-github/history.md
Module parse failed: /Users/user-mac/Desktop/workspace/test/www/node_modules/mdast-github/history.md Line 7: Unexpected number
You may need an appropriate loader to handle this file type.
| 
|
| 1.0.0 / 2015-08-19
| ==================
|
 @ ./~/mdast-github ^\.\/.*$

WARNING in ./~/mdast-github/package.json
Module parse failed: /Users/user-mac/Desktop/workspace/test/www/node_modules/mdast-github/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "_args": [
|     [
|       "mdast-github",
 @ ./~/mdast-github ^\.\/.*$

WARNING in ./~/mdast-github/readme.md
Module parse failed: /Users/user-mac/Desktop/workspace/test/www/node_modules/mdast-github/readme.md Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| # mdast-github [![Build Status](https://img.shields.io/travis/wooorm/mdast-github.svg)](https://travis-ci.org/wooorm/mdast-github) [![Coverage Status](https://img.shields.io/codecov/c/github/wooorm/mdast-github.svg)](https://codecov.io/github/wooorm/mdast-github)
|
| Auto-link references to commits, issues, pull-requests, and users like GitHub: [Writing on GitHub](https://help.github.com/articles/writing-on-github/#references).
 @ ./~/mdast-github ^\.\/.*$
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
Hash: e08bf16a6fc25d471f1f
Version: webpack 1.12.9
Time: 346ms

**Comment by wooorm** [comment]
This is something relating to webpack. Check out these docs: <https://github.com/webpack/docs/wiki/webpack-for-browserify-users#ignore-missing>.
As I understand from them, you can ignore these warnings.

**Comment by whisper-bye** [comment]
@wooorm 
one more thing, how to parse gfm style task lists by using mdast-html, the output looks like general lists

**Comment by wooorm** [comment]
Seems so. It’s not yet implemented in mdast-html. If you’d like to get this, please raise an issue on mdast-html’s repo.

**Comment by whisper-bye** [comment]
I'm giving up...
